#!/usr/bin/env bash

GW="$(/usr/bin/env ip route show | awk '/default/ {print $3}' | head -n1)"
VPNNET=$(sed -e 's/ //g' -e '/^vpnnet/I!d' -re 's/^(vpnnet|vpnnet=)//I' < "/etc/tinc/$NETNAME/tinc.conf" | head -n1)

# own routes
if [ "$NAME" == "$NODE" ]; then
  echo "Not adding our own route (${SUBNET})"
  exit 0
fi

# scope link
if /usr/bin/env ip route show | grep 'scope link' | grep -q "$SUBNET"; then
    echo "Not adding scope link route ($SUBNET)"
    exit 0
fi

# vpn subnet
if "/etc/tinc/${NETNAME}/subnet.pl" "${SUBNET%/32}" "$VPNNET"; then
    echo "Not adding vpn internal routes (${SUBNET})"
    exit 0
fi

# blacklist
if [ -f "/etc/tinc/${NETNAME}/blacklist" ]; then
    if sed -n -e "/^\[${GW}\]$/,/^\[.*\]$/{ /^\[${GW}\]$/d; /^\[.*\]$/d; p; }" "/etc/tinc/${NETNAME}/blacklist" | grep -q "$SUBNET"; then
        echo "Not adding blacklisted route ($SUBNET)"
        exit 0
    fi
fi

/usr/bin/env ip route add "$SUBNET" dev "$INTERFACE" metric "${WEIGHT:-100}"

if [ -x "/etc/tinc/${NETNAME}/subnet-up.local" ]; then
    "/etc/tinc/${NETNAME}/subnet-up.local" "$SUBNET" "$INTERFACE" "${WEIGHT:-100}"
fi
