#!/usr/bin/env bash

/usr/bin/env ip route del "$SUBNET" dev "$INTERFACE" metric "${WEIGHT:-10}"

if [ -x "/etc/tinc/${NETNAME}/subnet-down.local" ]; then
    "/etc/tinc/${NETNAME}/subnet-down.local" "$SUBNET" "$INTERFACE" "${WEIGHT:-10}"
fi
