#!/bin/bash

IP=$(sed -e 's/ //g' -e '/^subnet/I!d' -re 's/^(subnet|subnet=)//I' < "/etc/tinc/$NETNAME/hosts/$NAME" | head -n1)

/usr/bin/env ip link set "$INTERFACE" up
/usr/bin/env ip addr add "$IP" dev "$INTERFACE"
